---
theme: minima
google_analytics: UA-88738231-3
author: Stonic.io
twitter_username: stonicproject
github_username: stonicio
gems:
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-titles-from-headings
...